### Get all gifts
GET http://localhost:3000/gifts

### Get a single gift by ID
GET http://localhost:3000/gifts/#id

### Create a new gift
POST http://localhost:3000/gifts HTTP/1.1
Content-Type: application/json

{
    "name": "Knife Set",
    "price": "879.95",
    "department": "Kitchenware",
    "brand": "Henckels",
    "quantity": "1",
    "color": "Stainless Steel",
    "size": "Medium",
    "store": "Crate & Barrel"
}

### Update an existing gift by ID
PUT http://localhost:3000/gifts/69241248833014ec06d71dd5 HTTP/1.1
Content-Type: application/json

{
    "name": "Blinds",
    "price": "92.94",
    "department": "Home Decor",
    "brand": "Bali",
    "quantity": "1",
    "color": "White",
    "size": "Medium",
    "store": "Home Depot"
}

### Delete an pet by ID
DELETE http://localhost:3000/gifts/69240c43f6f1c7355eb46d13